# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yenor Needs Love Fund
email: yenorneedslovefund@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Here at Yenor Needs Love Fund we are passionate about finding a love for Yenor. This way he can retire from meming.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yenorneedslovefund.com" # the base hostname & protocol for your site
twitter_username: YenorLover
github_username:  YenorLover

# Build settings
markdown: kramdown
